### PR TITLE
words to number completed

### PR DESCRIPTION
**Pull request by payam-zahedi**
Words to number feature completed.
Note: the fuzzy option not implemented yet

the example would be something like this:
```dart
final words = 'سه هزار دویست و دوازده';

/// use [wordsToNumber] method to convert [words] to int number
wordsToNumber(words); // 3212

/// use [wordsToNumberString] method to convert [words] to String
wordsToNumberString(words); // '3212' as String

/// [wordsToNumberString] also has two optional parameter
/// use [digit] optional parameter to convert the digits to specific local digits
/// use [addComma] to add comma between the every 3 digits
wordsToNumberString(
words,
digits: DigitLocale.fa,
addComma: true,
); // '۳,۲۱۲' as String

/// or you can easily use extension methods on String object
words.convertWordsToNumber(); // 3212

words.convertWordsToNumberString(); // '3212' as String
```

### CODE REVIEW

**Comment by payam-zahedi** [comment]
I also improved some other features like `convertEnToAr` digits.

**Review by EhsanAramide — COMMENTED** [review]
well done, all are good

**Comment by ali-master** [comment]
Thanks, and it has done successfully. I have a suggestion, I think Dart has a `toString` method that helps you and there is no need to create another method like `convertWordsToNumberString` to do the same. Is it true?

**Comment by payam-zahedi** [comment]
Hi @ali-master, It's true in the dart we have `toString` method that convert every object to string type. But, we need to use the `convertWordsToNumberString` as separated method because it will give us more capabilities. Like adding `ordinalSuffix` or converting `digit` characters to specific language digits.

**Comment by ali-master** [comment]
If anyone wants to do that, they can convert number to string. Agree?

**Pull request merged**
