### PR TITLE
update bank constants

### PR DESCRIPTION
**Pull request by MahdiGharooni**
Added two new banks name (Noor, Khavarmiane) to bankInformation constants

### CODE REVIEW

**Comment by payam-zahedi** [comment]
Hi @MahdiGharooni thanks for your contribution.
Can you add some unit test for the newly added banks?

**Comment by MahdiGharooni** [comment]
You're welcome.
You mean write test in **test/test_get_bank_name_from_card_number.dart** file?

**Comment by payam-zahedi** [comment]
I'm not sure about the test file.
I should check the usage of the changed file.

**Comment by payam-zahedi** [comment]
@MahdiGharooni That's right. You should update this file test/test_get_bank_name_from_card_number.dart and add some test case for your changes.

**Comment by payam-zahedi** [comment]
مهدی لطفا برنچ تارگتت رو هم بزار روی dev

**Comment by MahdiGharooni** [comment]
I've added the new test cases for my changes. Please check whether it is merged into dev or not.

**Review by payam-zahedi — APPROVED** [review]
Well done Mahdi.
It works like a charm.

**Comment by payam-zahedi** [comment]
@MahdiGharooni 
checkout the new version
https://pub.dev/packages/persian_tools/changelog

**Comment by MahdiGharooni** [comment]
That's right. 
Thank you.

**Pull request merged**
