### PR TITLE
national id validation feature implemented

### PR DESCRIPTION
**Pull request by payam-zahedi**

### CODE REVIEW

**Comment by EhsanAramide** [comment]
extension methods are great but at the first level, we should create a feather as a function and then create an extension method of the feature in the dev branch then merge it to master.
I think extension method isn't a good idea for this feature because we can use it on all of `String`s instead of that we can declare a method with the Object class instance to give both `int` and `String`.

**Comment by payam-zahedi** [comment]
Since the national code can start with the `0` character we can't use the `int` instance for it. so in dart language, the only option that we have is the `String` class. for the `extension functions` and `dev` branch, I think we need a meet to talk about it.

**Review by EhsanAramide — COMMENTED** [review]
All changes are true but in lib/src/national_id.dart must have a function version beside extension method.

**Comment by payam-zahedi** [comment]
@EhsanAramide I refactored this feature and migrated it with new package style

**Review by EhsanAramide — COMMENTED** [review]
well done.merged to master.

**Pull request merged**
